### ISSUE TITLE
vagrant up fails due to following error. 

### ISSUE THREAD

**Issue by jarjis** [percona/xtradb-cluster-tutorial#3]
puppet provisioner:
- The following settings shouldn't exist: pp_path

The box link in the vagrant file is not working. I switched it to http://developer.nrel.gov/downloads/vagrant-boxes/CentOS-6.4-i386-v20130731.box"

**Comment by utdrmac** [comment]
If this is still an issue with latest HEAD, please re-open and I'll investigate.
