### ISSUE TITLE
Cluster installation fails.

### ISSUE THREAD

**Issue by jarjis** [percona/xtradb-cluster-tutorial#5]
vagrant up
Bringing machine 'node1' up with 'virtualbox' provider...
Bringing machine 'node2' up with 'virtualbox' provider...
Bringing machine 'node3' up with 'virtualbox' provider...
[node1] Importing base box 'centos6.4-i386-minimal'...
[node1] Matching MAC address for NAT networking...
[node1] Setting the name of the VM...
[node1] Clearing any previously set forwarded ports...
[node1] Creating shared folders metadata...
[node1] Clearing any previously set network interfaces...
[node1] Preparing network interfaces based on configuration...
[node1] Forwarding ports...
[node1] -- 22 => 2222 (adapter 1)
[node1] Running 'pre-boot' VM customizations...
[node1] Booting VM...
[node1] Waiting for machine to boot. This may take a few minutes...
[node1] Machine booted and ready!
[node1] The guest additions on this VM do not match the installed version of
VirtualBox! In most cases this is fine, but in rare cases it can
cause things such as shared folders to not work properly. If you see
shared folder errors, please update the guest additions within the
virtual machine and reload your VM.

Guest Additions Version: 4.2.16
VirtualBox Version: 4.3
[node1] Setting hostname...
[node1] Configuring and enabling network interfaces...
[node1] Mounting shared folders...
[node1] -- /vagrant
[node1] -- /tmp/vagrant-puppet/manifests
[node1] -- /tmp/vagrant-puppet/modules-0
[node1] Running provisioner: puppet...
Running Puppet with master_slave.pp...
Info: Loading facts in /tmp/vagrant-puppet/modules-0/mysql/lib/facter/mysql.rb
Warning: Could not retrieve fact fqdn
Warning: Host is missing hostname and/or domain: node1
Warning: Config file /etc/puppet/hiera.yaml not found, using Hiera defaults
Warning: Variable access via 'serverid' is deprecated. Use '@serverid' instead. template[/tmp/vagrant-puppet/modules-0/percona/templates/my.cnf.erb]:4
   (at /tmp/vagrant-puppet/modules-0/percona/templates/my.cnf.erb:4:in `result')
Warning: Variable access via 'hostname' is deprecated. Use '@hostname' instead. template[/tmp/vagrant-puppet/modules-0/percona/templates/my.cnf.erb]:9
   (at /tmp/vagrant-puppet/modules-0/percona/templates/my.cnf.erb:9:in`result')
Info: Loading facts in /tmp/vagrant-puppet/modules-0/mysql/lib/facter/mysql.rb
Info: Applying configuration version '1387217850'
Notice: /Stage[main]/Misc/Service[iptables]/ensure: ensure changed 'running' to 'stopped'
Notice: /Stage[main]/Misc/Exec[wget http://downloads.mysql.com/docs/sakila-db.zip]/returns: executed successfully
Notice: /Stage[main]/Misc/Package[screen]/ensure: created
Notice: /Stage[main]/Misc/Exec[myq_gadgets]/returns: executed successfully
Notice: /Stage[main]/Misc/Host[node2]/ensure: created
Info: FileBucket adding {md5}42e07b94c2eda4e78b010a1347225f68
Notice: /Stage[main]/Misc/File[/usr/local/bin/baseline_haproxy.sh]/ensure: defined content as '{md5}864c424ea9247e2cd60ea15cc2220a42'
Notice: /Stage[main]/Misc/Package[ntp]/ensure: created
Notice: /Stage[main]/Misc/File[/usr/local/bin/quick_update.pl]/ensure: defined content as '{md5}c0a36052dfb930b85f7da48390b63681'
Notice: /Stage[main]/Misc/Package[man]/ensure: created
Info: create new repo percona in file /etc/yum.repos.d/percona.repo
Notice: /Stage[main]/Percona::Repository/Yumrepo[percona]/descr: descr changed '' to 'Percona'
Notice: /Stage[main]/Percona::Repository/Yumrepo[percona]/baseurl: baseurl changed '' to 'http://repo.percona.com/centos/6/os/i386/'
Notice: /Stage[main]/Percona::Repository/Yumrepo[percona]/enabled: enabled changed '' to '1'
Notice: /Stage[main]/Percona::Repository/Yumrepo[percona]/gpgcheck: gpgcheck changed '' to '0'
Info: changing mode of /etc/yum.repos.d/percona.repo from 600 to 644
Notice: /Stage[main]/Percona::Toolkit/Package[perl-TermReadKey]/ensure: created
Notice: /Stage[main]/Misc/Host[node3]/ensure: created
Notice: /Stage[main]/Misc/Package[telnet]/ensure: created
Notice: /Stage[main]/Misc/Host[node1]/ip: ip changed '127.0.0.1' to '192.168.70.2'
Notice: /Stage[main]/Misc/Package[lsof]/ensure: created
Notice: /Stage[main]/Percona::Toolkit/Package[perl-Time-HiRes]/ensure: created
Info: FileBucket adding {md5}8ace886bbe7e274448bc8bea16d3ead6
Info: /Stage[main]/Percona::Server::Config/File[/etc/my.cnf]: Filebucketed /etc/my.cnf to puppet with sum 8ace886bbe7e274448bc8bea16d3ead6
Notice: /Stage[main]/Percona::Server::Config/File[/etc/my.cnf]/content: content changed '{md5}8ace886bbe7e274448bc8bea16d3ead6' to '{md5}76fd48e01740106bcb295883ddf39a5b'
Notice: /Stage[main]/Percona::Server::Packages/Package[Percona-Server-shared-55.i686]/ensure: created
Notice: /Stage[main]/Percona::Server::Packages/Package[Percona-Server-server-55.i686]/ensure: created
Notice: /Stage[main]/Percona::Server::Packages/Package[Percona-Server-shared-compat]: Dependency Package[mysql-libs] has failures: true
Notice: /Stage[main]/Misc/Exec[sysbench]: Dependency Package[mysql-libs] has failures: true
Error: Execution of '/bin/rpm -e mysql-libs-5.1.66-2.el6_3.i686' returned 1: error: package mysql-libs-5.1.66-2.el6_3.i686 is not installed

Error: /Stage[main]/Percona::Server::Packages/Package[mysql-libs]/ensure: change from 5.1.66-2.el6_3 to absent failed: Execution of '/bin/rpm -e mysql-libs-5.1.66-2.el6_3.i686' returned 1: error: package mysql-libs-5.1.66-2.el6_3.i686 is not installed

Warning: /Stage[main]/Percona::Server::Packages/Package[Percona-Server-shared-compat]: Skipping because of failed dependencies
Warning: /Stage[main]/Misc/Exec[sysbench]: Skipping because of failed dependencies
Notice: /Stage[main]/Misc/File[/root/sysbench_tests]: Dependency Package[mysql-libs] has failures: true
Warning: /Stage[main]/Misc/File[/root/sysbench_tests]: Skipping because of failed dependencies
Notice: /Stage[main]/Percona::Toolkit/Package[perl-DBD-MySQL]: Dependency Package[mysql-libs] has failures: true
Warning: /Stage[main]/Percona::Toolkit/Package[perl-DBD-MySQL]: Skipping because of failed dependencies
Notice: /Stage[main]/Percona::Server::Service/Service[mysql]: Dependency Package[mysql-libs] has failures: true
Warning: /Stage[main]/Percona::Server::Service/Service[mysql]: Skipping because of failed dependencies
Notice: /Stage[main]/Misc/File[/usr/local/bin/baseline.sh]/ensure: defined content as '{md5}b23ac2850ab10e76f4d8858563a00cfa'
Notice: /Stage[main]//Node[node1]/Exec[replication-user]: Dependency Package[mysql-libs] has failures: true
Warning: /Stage[main]//Node[node1]/Exec[replication-user]: Skipping because of failed dependencies
Notice: /Stage[main]/Misc/Package[unzip]/ensure: created
Notice: /Stage[main]/Misc/File[/root/bin]/mode: mode changed '0755' to '0775'
Notice: /Stage[main]/Misc/Service[ntpd]/ensure: ensure changed 'stopped' to 'running'
Info: /Stage[main]/Misc/Service[ntpd]: Unscheduling refresh on Service[ntpd]
Notice: /Stage[main]/Percona::Toolkit/Package[percona-toolkit]: Dependency Package[mysql-libs] has failures: true
Warning: /Stage[main]/Percona::Toolkit/Package[percona-toolkit]: Skipping because of failed dependencies
Info: Creating state file /var/lib/puppet/state/state.yaml
Notice: Finished catalog run in 271.22 seconds
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

puppet apply --verbose --modulepath '/etc/puppet/modules:/tmp/vagrant-puppet/modules-0' --manifestdir /tmp/vagrant-puppet/manifests --detailed-exitcodes /tmp/vagrant-puppet/manifests/master_slave.pp || [ $? -eq 2 ]

Stdout from the command:

Info: Loading facts in /tmp/vagrant-puppet/modules-0/mysql/lib/facter/mysql.rb
Info: Loading facts in /tmp/vagrant-puppet/modules-0/mysql/lib/facter/mysql.rb
Info: Applying configuration version '1387217850'
Notice: /Stage[main]/Misc/Service[iptables]/ensure: ensure changed 'running' to 'stopped'
Notice: /Stage[main]/Misc/Exec[wget http://downloads.mysql.com/docs/sakila-db.zip]/returns: executed successfully
Notice: /Stage[main]/Misc/Package[screen]/ensure: created
Notice: /Stage[main]/Misc/Exec[myq_gadgets]/returns: executed successfully
Notice: /Stage[main]/Misc/Host[node2]/ensure: created
Info: FileBucket adding {md5}42e07b94c2eda4e78b010a1347225f68
Notice: /Stage[main]/Misc/File[/usr/local/bin/baseline_haproxy.sh]/ensure: defined content as '{md5}864c424ea9247e2cd60ea15cc2220a42'
Notice: /Stage[main]/Misc/Package[ntp]/ensure: created
Notice: /Stage[main]/Misc/File[/usr/local/bin/quick_update.pl]/ensure: defined content as '{md5}c0a36052dfb930b85f7da48390b63681'
Notice: /Stage[main]/Misc/Package[man]/ensure: created
Info: create new repo percona in file /etc/yum.repos.d/percona.repo
Notice: /Stage[main]/Percona::Repository/Yumrepo[percona]/descr: descr changed '' to 'Percona'
Notice: /Stage[main]/Percona::Repository/Yumrepo[percona]/baseurl: baseurl changed '' to 'http://repo.percona.com/centos/6/os/i386/'
Notice: /Stage[main]/Percona::Repository/Yumrepo[percona]/enabled: enabled changed '' to '1'
Notice: /Stage[main]/Percona::Repository/Yumrepo[percona]/gpgcheck: gpgcheck changed '' to '0'
Info: changing mode of /etc/yum.repos.d/percona.repo from 600 to 644
Notice: /Stage[main]/Percona::Toolkit/Package[perl-TermReadKey]/ensure: created
Notice: /Stage[main]/Misc/Host[node3]/ensure: created
Notice: /Stage[main]/Misc/Package[telnet]/ensure: created
Notice: /Stage[main]/Misc/Host[node1]/ip: ip changed '127.0.0.1' to '192.168.70.2'
Notice: /Stage[main]/Misc/Package[lsof]/ensure: created
Notice: /Stage[main]/Percona::Toolkit/Package[perl-Time-HiRes]/ensure: created
Info: FileBucket adding {md5}8ace886bbe7e274448bc8bea16d3ead6
Info: /Stage[main]/Percona::Server::Config/File[/etc/my.cnf]: Filebucketed /etc/my.cnf to puppet with sum 8ace886bbe7e274448bc8bea16d3ead6
Notice: /Stage[main]/Percona::Server::Config/File[/etc/my.cnf]/content: content changed '{md5}8ace886bbe7e274448bc8bea16d3ead6' to '{md5}76fd48e01740106bcb295883ddf39a5b'
Notice: /Stage[main]/Percona::Server::Packages/Package[Percona-Server-shared-55.i686]/ensure: created
Notice: /Stage[main]/Percona::Server::Packages/Package[Percona-Server-server-55.i686]/ensure: created
Notice: /Stage[main]/Percona::Server::Packages/Package[Percona-Server-shared-compat]: Dependency Package[mysql-libs] has failures: true
Notice: /Stage[main]/Misc/Exec[sysbench]: Dependency Package[mysql-libs] has failures: true
Notice: /Stage[main]/Misc/File[/root/sysbench_tests]: Dependency Package[mysql-libs] has failures: true
Notice: /Stage[main]/Percona::Toolkit/Package[perl-DBD-MySQL]: Dependency Package[mysql-libs] has failures: true
Notice: /Stage[main]/Percona::Server::Service/Service[mysql]: Dependency Package[mysql-libs] has failures: true
Notice: /Stage[main]/Misc/File[/usr/local/bin/baseline.sh]/ensure: defined content as '{md5}b23ac2850ab10e76f4d8858563a00cfa'
Notice: /Stage[main]//Node[node1]/Exec[replication-user]: Dependency Package[mysql-libs] has failures: true
Notice: /Stage[main]/Misc/Package[unzip]/ensure: created
Notice: /Stage[main]/Misc/File[/root/bin]/mode: mode changed '0755' to '0775'
Notice: /Stage[main]/Misc/Service[ntpd]/ensure: ensure changed 'stopped' to 'running'
Info: /Stage[main]/Misc/Service[ntpd]: Unscheduling refresh on Service[ntpd]
Notice: /Stage[main]/Percona::Toolkit/Package[percona-toolkit]: Dependency Package[mysql-libs] has failures: true
Info: Creating state file /var/lib/puppet/state/state.yaml
Notice: Finished catalog run in 271.22 seconds

Stderr from the command:

Warning: Could not retrieve fact fqdn
Warning: Host is missing hostname and/or domain: node1
Warning: Config file /etc/puppet/hiera.yaml not found, using Hiera defaults
Warning: Variable access via 'serverid' is deprecated. Use '@serverid' instead. template[/tmp/vagrant-puppet/modules-0/percona/templates/my.cnf.erb]:4
   (at /tmp/vagrant-puppet/modules-0/percona/templates/my.cnf.erb:4:in `result')
Warning: Variable access via 'hostname' is deprecated. Use '@hostname' instead. template[/tmp/vagrant-puppet/modules-0/percona/templates/my.cnf.erb]:9
   (at /tmp/vagrant-puppet/modules-0/percona/templates/my.cnf.erb:9:in`result')
Error: Execution of '/bin/rpm -e mysql-libs-5.1.66-2.el6_3.i686' returned 1: error: package mysql-libs-5.1.66-2.el6_3.i686 is not installed

Error: /Stage[main]/Percona::Server::Packages/Package[mysql-libs]/ensure: change from 5.1.66-2.el6_3 to absent failed: Execution of '/bin/rpm -e mysql-libs-5.1.66-2.el6_3.i686' returned 1: error: package mysql-libs-5.1.66-2.el6_3.i686 is not installed

Warning: /Stage[main]/Percona::Server::Packages/Package[Percona-Server-shared-compat]: Skipping because of failed dependencies
Warning: /Stage[main]/Misc/Exec[sysbench]: Skipping because of failed dependencies
Warning: /Stage[main]/Misc/File[/root/sysbench_tests]: Skipping because of failed dependencies
Warning: /Stage[main]/Percona::Toolkit/Package[perl-DBD-MySQL]: Skipping because of failed dependencies
Warning: /Stage[main]/Percona::Server::Service/Service[mysql]: Skipping because of failed dependencies
Warning: /Stage[main]//Node[node1]/Exec[replication-user]: Skipping because of failed dependencies
Warning: /Stage[main]/Percona::Toolkit/Package[percona-toolkit]: Skipping because of failed dependencies

**Comment by utdrmac** [comment]
If this is still an issue with the latest HEAD, please re-open.
