### ISSUE TITLE
NameError: uninitialized constant Vagrantfile

### ISSUE THREAD

**Issue by nirmalbaral** [percona/xtradb-cluster-tutorial#8]
In windows 10, running `vagrant up` throws following error

There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
a syntax error.

Path:/xtradb-cluster-tutorial/Vagrantfile
Line number: 1
Message: NameError: uninitialized constant Vagrantfile

**Comment by utdrmac** [comment]
Make sure `Vagrantfile` exists. On linux, this is done as a symlink to an existing Vagrantfile.* Unfortunately, I don't have Windows 10 to test this on. Please re-open if you continue to experience this issue and I will try to help.
